name: Go

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: build
      uses: gha-devops/cicd/go-build@v1
    
    - uses: gha-devops/cicd/build-docker@v1
      id: docker-build
      with:
        access-key: ${{ secrets.AWS_ACCESS_KEY }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ secrets.AWS_REGION }}
        ecr-repository: ${{ secrets.ECR_REPOSITORY }}
        image-name: ${{ github.repository }}
        image-tag: ${{ github.sha }}      
